---
- name: Add YUM sbt repo
  yum_repository:
    name: sbt
    baseurl: https://sbt.bintray.com/rpm
    gpgcheck: no
    repo_gpgcheck: no
    description: Scala Build Tool

- name: Install packages
  yum:
    name:
      - sbt
    version:
      - 0.13.16-0
    state: present